wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695325206.705238
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 77
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 77
      3:
      - 1
      - 13
      - 19
      - 23
      4: 3.10.6
      5: 0.15.9
      6: 4.32.1
      8:
      - 5
trainer_fs:
  desc: null
  value: true
params:
  desc: null
  value:
    root: ~/Datasets
    dataset: arxiv
    invalidate_cache: false
    dataset_len_cap: 510
    val_len_cap: 510
    test_len_cap: 500
    shuffle_index: false
    force_cache: false
    classification_only: false
    early_stopping_patience: 20
    reset_after_layer: null
    original_features: false
    override_log: false
    seed: null
    metric: Acc
    learning_rate: 1.0e-05
    epochs: 1
    print_epoch: 10
    eval_epoch: 10
    checkpoint_epoch: 10
    print_step: 2000
    eval_step: 100
    checkpoint_step: 2000
    batch_size: 5
    weight_decay: 0.001
    dropout: 0
    text_features_dropout: 0
    rel_sample_random_seed: null
    split_train_nodes: false
    verbose: false
    workers: 10
    device: cuda:1
    input_dim: 768
    emb_dim: 256
    gnn_type: sage
    n_layer: 1
    meta_n_layer: 1
    second_gnn: Atten
    attention_mask_scheme: causal
    skip_path: false
    has_final_back: false
    layers: S2,U,M
    ignore_label_embeddings: true
    zero_label_embeddings: false
    not_freeze_learned_label_embedding: false
    linear_probe: false
    fix_datasets_first: false
    no_bn_metagraph: false
    no_bn_encoder: false
    calc_ranks: false
    eval_only: true
    meta_gnn_pos_only: false
    task_name: classification
    zero_shot: false
    no_split_labels: true
    all_test: false
    train_cap: 10
    label_set: null
    csr_split: false
    n_way: 3
    n_shots: 3
    n_query: 3
    n_way_upper: -1
    n_shots_upper: -1
    n_query_upper: -1
    max_length: -1
    augmentation: ''
    augment_test: false
    attr_regression_weight: 0.0
    prefix: exp1
    timestamp: '22_09_2023_01_01_48'
    log_dir: log
    state_dir: state
    bert_emb_model: roberta-base-nli-stsb-mean-tokens
    bert_cache: multi-qa-distilbert-cos-v1
    kg_emb_model: ''
    pretrained_model_run: ./state/MAG_PT_PRODIGY_04_09_2023_08_59_31/state_dict
    small_dataset: false
    experiment_type: metagraph
    exp_name: exp1_22_09_2023_01_01_48
